name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to DockerHUB
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: your-dockerhub-username/your-portfolio-app:latest

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: <your-aws-account-id>.dkr.ecr.<your-region>.amazonaws.com
          region: <your-region>

      - name: Build and push Docker image to AWS ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: <your-aws-account-id>.dkr.ecr.<your-region>.amazonaws.com/your-portfolio-app:latest
